site_name: AllenDocs
nav:
    - Home: index.md
    - Fy12b: fy12b.md
    - GitUsage: gitusage.md
    - Openwrt: openwrt.md
    - Iptables: iptables.md
    - FfmpegUsage: ffmpegusage.md
    - Aptusage: aptusage.md
    - GitLabUsage: gitlabusage.md
    - LinuxCommand: linuxcommand.md
    - Cryptography: cryptography.md
    - Electron: electron.md
    - Nginx: nginx.md
    - Django: django.md
    - Database: database.md
    - Android: android.md
    - Uwsgi: uwsgi.md
    - Avalonia: avalonia.md
    - Regex: regex.md
    - CodeSigning: codesigning.md

theme:
  name: material
  features:
    - content.code.copy

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences



