site_name: AllenDocs
nav:
    - Home: index.md
    - Fy12b: fy12b.md
    - GitUsage: gitusage.md
    - Openwrt: openwrt.md
    - Iptables: iptables.md
    - ffmpegUsage: ffmpegusage.md
    - About: about.md

theme:
  name: material
  features:
    - content.code.copy

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences



